import type { Prisma } from "@/generated/prisma/client";
import { db } from "@/lib/db";

// Aktions-Konstanten – zentral definiert, um Tippfehler zu vermeiden.
export const AUDIT = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
  USER_ANONYMIZED: "USER_ANONYMIZED",
  TICKET_CLOSED: "TICKET_CLOSED",
  TICKET_REOPENED: "TICKET_REOPENED",
  TICKET_EXTERNAL_RELEASED: "TICKET_EXTERNAL_RELEASED",
  DSGVO_EXPORT: "DSGVO_EXPORT",
  // Plattform-Betreiber (/plattform)
  PLATFORM_ACCESS: "PLATFORM_ACCESS",
  PLATFORM_ORG_DEACTIVATED: "PLATFORM_ORG_DEACTIVATED",
  PLATFORM_ORG_REACTIVATED: "PLATFORM_ORG_REACTIVATED",
  PLATFORM_ORG_PLAN_CHANGED: "PLATFORM_ORG_PLAN_CHANGED",
  PLATFORM_TRIAL_EXTENDED: "PLATFORM_TRIAL_EXTENDED",
  PLATFORM_NOTE_SAVED: "PLATFORM_NOTE_SAVED",
  PLATFORM_INVOICE_CREATED: "PLATFORM_INVOICE_CREATED",
  PLATFORM_INVOICE_STATUS: "PLATFORM_INVOICE_STATUS",
  PLATFORM_INVOICE_DOWNLOADED: "PLATFORM_INVOICE_DOWNLOADED",
  PLATFORM_INVOICE_SENT: "PLATFORM_INVOICE_SENT",
  PLATFORM_INVOICE_REMINDER: "PLATFORM_INVOICE_REMINDER",
  PLATFORM_IMPERSONATE_START: "PLATFORM_IMPERSONATE_START",
  PLATFORM_IMPERSONATE_STOP: "PLATFORM_IMPERSONATE_STOP",
  // WEG-Finanzen (Selbstverwaltung)
  WEG_FINANCE_SETTINGS_SAVED: "WEG_FINANCE_SETTINGS_SAVED",
  WEG_UNIT_SAVED: "WEG_UNIT_SAVED",
  WEG_COSTTYPE_SAVED: "WEG_COSTTYPE_SAVED",
  WEG_COST_CATALOG_ADOPTED: "WEG_COST_CATALOG_ADOPTED",
  WEG_ACCOUNT_SAVED: "WEG_ACCOUNT_SAVED",
  WEG_BOOKING_CREATED: "WEG_BOOKING_CREATED",
  WEG_TRANSFER_CREATED: "WEG_TRANSFER_CREATED",
  WEG_BANK_IMPORT: "WEG_BANK_IMPORT",
  WEG_PLAN_SAVED: "WEG_PLAN_SAVED",
  WEG_PLAN_DELETED: "WEG_PLAN_DELETED",
  WEG_PLAN_RESOLVED: "WEG_PLAN_RESOLVED",
  WEG_PAYMENT_ASSIGNED: "WEG_PAYMENT_ASSIGNED",
  WEG_UNIT_OWNERSHIP_SAVED: "WEG_UNIT_OWNERSHIP_SAVED",
  WEG_STATEMENT_SAVED: "WEG_STATEMENT_SAVED",
  WEG_STATEMENT_DELETED: "WEG_STATEMENT_DELETED",
  WEG_STATEMENT_FINALIZED: "WEG_STATEMENT_FINALIZED",
  WEG_MAHNUNG_CREATED: "WEG_MAHNUNG_CREATED",
  WEG_MAHNUNG_SENT: "WEG_MAHNUNG_SENT",
  WEG_MAHNUNG_DELETED: "WEG_MAHNUNG_DELETED",
} as const;

// Schreibt einen Audit-Log-Eintrag. Wirft nie – ein Logging-Fehler darf den
// Hauptfluss nicht unterbrechen.
export async function logAudit(params: {
  actorId?: string | null;
  action: string;
  targetType?: string;
  targetId?: string;
  meta?: Record<string, unknown>;
  ip?: string;
}): Promise<void> {
  try {
    await db.auditLog.create({
      data: {
        actorId: params.actorId ?? null,
        action: params.action,
        targetType: params.targetType ?? null,
        targetId: params.targetId ?? null,
        meta: (params.meta ?? undefined) as Prisma.InputJsonObject | undefined,
        ip: params.ip ?? null,
      },
    });
  } catch {
    // intentionally silent
  }
}
